repos:
  - repo: local
    hooks:
      - id: dprint
        name: dprint 
        entry: dprint fmt
        language: system
        types: [markdown]
        require_serial: true
        pass_filenames: false
