repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check .
        args: [ --config, pyproject.toml, --fix, --show-fixes, --exit-non-zero-on-fix ]
        language: system
        types_or: [python]
        require_serial: true # run once for all files
        pass_filenames: false
      - id: black
        name: black
        entry: black
        language: system
        types_or: [python, pyi]
        require_serial: true # run once for all files
        exclude: ^tests/.*snapshots/
      - id: pyright
        name: pyright
        entry: pyright
        language: system
        types: [python]
        require_serial: true # run once for all files
        exclude: ^tests/.*snapshots/
